"""create initial tables

Revision ID: 05738b3709ba
Revises: 
Create Date: 2022-09-04 19:46:20.916374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05738b3709ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avatar')
    # ### end Alembic commands ###
